//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ModelFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int OrderNum { get; set; }
        public Nullable<int> EmpID { get; set; }
        public string Employee_Name { get; set; }
        public string Employee_Job_Title { get; set; }
        public string Sales_Region { get; set; }
        public Nullable<System.DateTime> OrderDate { get; set; }
        public string OrderType { get; set; }
        public string CustomerType { get; set; }
        public Nullable<short> Customer_ID { get; set; }
        public string CustName { get; set; }
        public string CustState { get; set; }
        public string ProdCategory { get; set; }
        public string ProdNumber { get; set; }
        public string ProdName { get; set; }
        public Nullable<short> Quantity { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string Discount { get; set; }
        public Nullable<decimal> Order_Total { get; set; }
    }
}
